name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        cd ./esp32-pwa-app/
        npm ci
        npm run build --if-present
      env:
        CI: true
    - name: Archive production build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: pwa-build-artifact
        path: |
          esp32-pwa-app/build
