name: Deploy

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
    branches:
      - main

jobs:
  infra:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Install infra dependencies
      run: npm i
      working-directory: infra
    - name: Pulumi Up
      uses: pulumi/actions@v3
      with:
        command: up
        stack-name: dev
        work-dir: infra
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

  deployment:
    needs: infra
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: Download build artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: build.yaml
        workflow_conclusion: success
        branch: main
        name: pwa-build-artifact
        path: ./build
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Copy build to S3 bucket
      run: |
        aws s3 sync build/ s3://${{ secrets.AWS_S3_BUCKET }}
    - name: Create CloudFront invalidation
      run: |
        aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DIST }} --paths "/*"
