name: Deploy

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - name: Download a single artifact
      uses: actions/download-artifact@v3
      with:
        name: pwa-build-artifact
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Copy build to S3 bucket
      run: |
        aws s3 sync build/ s3://${{ secrets.AWS_S3_BUCKET }}
    - name: Create CloudFront invalidation
      run: |
        aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DIST }} --paths "/*"
